services:
  - type: web
    name: python-ta-service
    env: python
    rootDir: python-ta-service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11